/** Art assets the scene planner may use. IDs are stable so saved stories survive. */
export const BACKDROPS = {
  steelhacks: 'The official SteelHacks XIII neon Pittsburgh skyline',
  forest: 'A sunlit fairy-tale forest with a winding path',
  meadow: 'A flower-filled open meadow',
  river: 'A sparkling riverside with a gentle shore',
  mountain: 'A high mountain valley and distant peaks',
  sky: 'A bright sky with clouds and floating islands',
  ocean: 'An underwater reef with sunbeams and bubbles',
  space: 'Outer space with stars and distant planets',
  classroom: 'A warm classroom with windows and a board',
  hackathon: 'A friendly makerspace with tables and screens',
  castle: 'A storybook castle courtyard',
  village: 'A cozy fairy-tale village street',
  cave: 'A glowing crystal cave',
  desert: 'A warm desert of dunes and an oasis',
  snowfield: 'A snowy valley with evergreens',
  library: 'A cozy library filled with books',
  kitchen: 'A bright storybook kitchen',
  city: 'A playful city square with colorful buildings',
  garden: 'A secret walled garden full of plants',
  island: 'A tropical island with a sandy shore',
  airship: 'The deck of a flying airship above the clouds',
  restroom: 'A clean, friendly restroom or bathroom with sinks, mirrors and stalls; also called washroom or toilet',
  bedroom: 'A cozy bedroom with a bed and window',
  playground: 'An outdoor playground with slides and swings',
  hospital: 'A gentle hospital or clinic room',
  museum: 'A museum gallery with exhibits and paintings',
  cafe: 'A warm cafe or bakery with small tables',
  trainstation: 'A train station platform with tracks',
  farm: 'A farm with a barn, fields and fences',
  beach: 'A sunny beach with waves and sand',
  jungle: 'A lush jungle with vines and broad leaves',
  swamp: 'A misty wetland with reeds and shallow water',
  volcano: 'A fantasy volcanic valley with glowing lava in the distance',
  laboratory: 'A friendly science laboratory with experiments',
  theater: 'A theater stage with curtains and spotlights',
  spaceship: 'The interior cockpit of a friendly spaceship',
} as const

export const PROPS = {
  tree: 'A leafy tree', flower: 'A flower patch', bridge: 'A small bridge',
  cottage: 'A cottage', tower: 'A tower', lantern: 'A lantern',
  cloud: 'A fluffy cloud', star: 'A bright star', planet: 'A ringed planet',
  rocket: 'A little rocket', coral: 'A coral cluster', fish: 'A fish',
  desk: 'A desk', laptop: 'A laptop', book: 'A book',
  banner: 'A colorful banner', crystal: 'A glowing crystal', door: 'A door',
  cactus: 'A desert cactus', snowman: 'A friendly snowman',
  bookshelf: 'A bookshelf', teapot: 'A teapot',
  telescope: 'A telescope', boat: 'A little boat',
  treasure: 'A treasure chest', mushroom: 'A spotted mushroom',
  clock: 'A clock', robot: 'A friendly robot',
  moon: 'A crescent moon', butterfly: 'A butterfly',
  toilet: 'A clean restroom toilet', sink: 'A sink with a faucet',
  mirror: 'A framed mirror', bathtub: 'A bathtub', towel: 'A folded towel',
  slide: 'A playground slide', swing: 'A playground swing',
  bed: 'A cozy bed', pillow: 'A soft pillow',
  firstaid: 'A first aid box', painting: 'A framed painting', fossil: 'A dinosaur fossil',
  pastry: 'A bakery pastry', train: 'A small train', suitcase: 'A travel suitcase',
  barn: 'A farm barn', tractor: 'A farm tractor', palm: 'A palm tree',
  seashell: 'A seashell', frog: 'A friendly frog',
  beaker: 'A science beaker', microscope: 'A microscope',
  curtain: 'A stage curtain', controlpanel: 'A spaceship control panel',
} as const

export type BackdropId = keyof typeof BACKDROPS
export type PropId = keyof typeof PROPS

export const BACKDROP_IDS = Object.keys(BACKDROPS) as BackdropId[]
export const PROP_IDS = Object.keys(PROPS) as PropId[]
